config/routes.rb
MjLatest::Application.routes.draw do
   root :to => 'advertisements#index'

  resources :advertisements

  resources :family_members

  resources :events

  resources :feedbacks

  resources :relations

  get 'site/team'
  match 'team' => 'site#team'

  get "site/festivals"
  match 'festivals' => 'site#festivals'

  get "site/histroy"
  match 'history' => 'site#histroy'

  get "site/vanshothpatti"
match 'vanshothpatti' => 'site#vanshothpatti'

  get "site/aboutus"
match 'aboutus' => 'site#aboutus'

  get "site/demofalimytree"
match 'demofalimytree' => 'site#demofalimytree'

  get "site/rajasthan"
match 'rajasthan' => 'site#rajasthan'

  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :advertisers
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  

end

app/views/relations (copy)/_form.html.erb
<%= simple_form_for(@relation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :relationship %>
    <%= f.input :priority %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/relations (copy)/edit.html.erb
<h1>Editing relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations (copy)/index.html.erb
<h1>Listing relations</h1>

<table>
  <tr>
    <th>Relationship</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relations.each do |relation| %>
  <tr>
    <td><%= relation.relationship %></td>
    <td><%= relation.priority %></td>
    <td><%= link_to 'Show', relation %></td>
    <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
    <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relation', new_relation_path %>

app/views/relations (copy)/new.html.erb
<h1>New relation</h1>

<%= render 'form' %>

<%= link_to 'Back', relations_path %>

app/views/relations (copy)/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Relationship:</b>
  <%= @relation.relationship %>
</p>

<p>
  <b>Priority:</b>
  <%= @relation.priority %>
</p>


<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>