config/routes.rb
MjLatest::Application.routes.draw do
   root :to => 'advertisements#index'

  resources :advertisements

  resources :family_members

  resources :events

  resources :feedbacks

  resources :relations

  get 'site/team'
  match 'team' => 'site#team'

  get "site/festivals"
  match 'festivals' => 'site#festivals'

  get "site/histroy"
  match 'history' => 'site#histroy'

  get "site/vanshothpatti"
match 'vanshothpatti' => 'site#vanshothpatti'

  get "site/aboutus"
match 'aboutus' => 'site#aboutus'

  get "site/demofalimytree"
match 'demofalimytree' => 'site#demofalimytree'

  get "site/rajasthan"
match 'rajasthan' => 'site#rajasthan'

  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :advertisers
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :details, :user_id
    belongs_to :user

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= simple_form_for(@feedback) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :details %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Details</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.details %></td>
    <td><%= feedback.user_id %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Details:</b>
  <%= @feedback.details %>
</p>

<p>
  <b>User:</b>
  <%= @feedback.user_id %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>